// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ContextDb))]
    partial class ContextDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.BallSkin", b =>
                {
                    b.Property<int>("id_BallSkin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_BallSkin"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("id_BallSkin");

                    b.ToTable("BallSkins");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Property<int>("id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_User"));

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_User");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApplication1.Models.UserSkin", b =>
                {
                    b.Property<int>("id_UserSkin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_UserSkin"));

                    b.Property<int?>("Userid_User")
                        .HasColumnType("integer");

                    b.Property<int>("ballSkin_id")
                        .HasColumnType("integer");

                    b.Property<bool>("isSelected")
                        .HasColumnType("boolean");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id_UserSkin");

                    b.HasIndex("Userid_User");

                    b.HasIndex("ballSkin_id");

                    b.ToTable("UserSkins");
                });

            modelBuilder.Entity("WebApplication1.Models.UserSkin", b =>
                {
                    b.HasOne("WebApplication1.Models.User", null)
                        .WithMany("userSkins")
                        .HasForeignKey("Userid_User");

                    b.HasOne("WebApplication1.Models.BallSkin", "ballSkin")
                        .WithMany("userSkins")
                        .HasForeignKey("ballSkin_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ballSkin");
                });

            modelBuilder.Entity("WebApplication1.Models.BallSkin", b =>
                {
                    b.Navigation("userSkins");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Navigation("userSkins");
                });
#pragma warning restore 612, 618
        }
    }
}
